XPs:

events:
  Registered: ~
  NewsRead: ~
  AvatarEdited:
    actions:
      - xp: XP
        amount: 1
  StudentGroupCreated:
    actions:
      - xp: XP
        amount: 2
  TopicCreated:
    actions:
      - xp: XP
        amount: 2
  MaterialShared:
    actions:
      - xp: XP
        amount: 10
  MaterialSearched:
    actions:
      - xp: XP
        amount: 10
  HomeWorkSubmitted:
    actions:
      - xp: XP
        amount: 5
  FunctionXUsed:
    actions:
      - xp: XP
        amount: 1
  FunctionYUsed:
    actions:
      - xp: XP
        amount: 1
  FunctionZUsed:
    actions:
      - xp: XP
        amount: 1

achievements:
  # TODO How to implement?
  ConstantVisitor: ~
  Registered:
    requirements:
      - event:
        name: Registered
        amount: 1
    actions:
      - xp: XP
        amount: 10
    scope: [user]
  FirstNewsRead:
    requirements:
      - event:
        name: NewsRead
        amount: 1
      actions:
        - xp: XP
          amount: 5
    scope: [user]
  AvatarCreativity1:
    requirements:
      - event:
        name: AvatarEdited
        amount: 1
  AvatarCreativity10:
    requirements:
      - event:
        name: AvatarEdited
        amount: 10
    actions:
      - xp: XP
        amount: 5
  AvatarCreativity25:
    requirements:
      - event:
        name: AvatarEdited
        amount: 25
    actions:
      - xp: XP
        amount: 15
  TeamPlayer:
    requrements:
      - event:
        name: StudentGroupCreated
        amount: 1
    actions:
      - xp: XP
        amount: 2
    scope: [user, context.course_id]
  TeamPlayer5:
    requrements:
      - event:
        name: StudentGroupCreated
        amount: 5
    actions:
      - xp: XP
        amount: 10
    scope: [user, context.course_id]
  TeamPlayer10:
    requrements:
      - event:
        name: StudentGroupCreated
        amount: 10
    actions:
      - xp: XP
        amount: 20
    scope: [user, context.course_id]
  TopicCreator:
    requirements:
      - event:
        name: TopicCreated
        amonut: 1
    actions:
      - xp: XP
        amount: 5
    scope: [user, context.student_group]
  TopicCreator5:
    requirements:
      - event:
        name: TopicCreated
        amonut: 5
    actions:
      - xp: XP
        amount: 10
    scope: [user, context.student_group]
  TopicCreator10:
    requirements:
      - event:
        name: TopicCreated
        amonut: 10
    actions:
      - xp: XP
        amount: 20
    scope: [user, context.student_group]
  Sharer:
    requirements:
      - event:
        name: MaterialShared
        amount: 1
    actions: 
      - xp: XP
        amount: 15
  Sharer5:
    requirements:
      - event:
        name: MaterialShared
        amount: 5
    actions: 
      - xp: XP
        amount: 25
  Sharer10:
    requirements:
      - event:
        name: MaterialShared
        amount: 10
    actions: 
      - xp: XP
        amount: 35
  Sharer:
    requirements:
      - event:
        name: MaterialShared
        amount: 1
    actions: 
      - xp: XP
        amount: 15
  Sharer5:
    requirements:
      - event:
        name: MaterialShared
        amount: 5
    actions: 
      - xp: XP
        amount: 25
  Sharer10:
    requirements:
      - event:
        name: MaterialShared
        amount: 10
    actions: 
      - xp: XP
        amount: 35
  Explorer:
    requirements:
      - event:
        name: MaterialSearched
        amount: 1
    actions: 
      - xp: XP
        amount: 15
  Explorer5:
    requirements:
      - event:
        name: MaterialSearched
        amount: 5
    actions: 
      - xp: XP
        amount: 25
  Explorer10:
    requirements:
      - event:
        name: MaterialSearched
        amount: 10
    actions: 
      - xp: XP
        amount: 35
  SchulCloudExpert:
    requirements:
      - event:
        name: FunctionXUsed
        amount: 1
      - event:
        name: FunctionYUsed
        amount: 1
      - event:
        name: FunctionZUsed
        amount: 1
    actions:
      - xp: XP
        amount: 40
    scope: [user]
  # Be the first who made a submission for a specific assignment
  # TODO check if this works
  HomeworkSubmissionFirst:
    requirements:
      - event:
        name: HomeworkSubmitted
        amount: 1
    actions:
      - xp: XP
        amount: 10
    scope: [context.assignment_id]